### ISSUE TITLE
Improve Documentation

### ISSUE THREAD

**Issue by percurnicus** [planetarypy/planetary_test_data#21]
I will need to document new features as well as better explanations on to to best use planetary_test_data. This should also include what missions and images are in data.json. Possibly, create a RTFD for the repo.

**Comment by tjslezak** [comment]
This is particularly important because instruments with "legacy" have high TRLs (Technology Readiness Levels) and are most often selected for future missions. E.g., Voyager NAC / WAC and LROC NAC/WAC, Pancam/Mastcam/MastcamZ, Mini-TES/TES/THEMIS, etc. Thus, the PDS instrument labels can easily be the same for entirely different missions.

**Comment by percurnicus** [comment]
I'm not sure how that relates to improving planetary_test_data documentation

**Comment by percurnicus** [comment]
Fixed in #27
